services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "4321:4321"
      - "9323:9323"
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: "./app"
        target: "/app"
